# Generated by Django 5.2.7 on 2025-10-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceWeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GEOMAGNETIC_STORM', 'Geomagnetic Storm'), ('SOLAR_FLARE', 'Solar Flare'), ('OTHER', 'Other')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('max_kp_index', models.FloatField(blank=True, null=True)),
                ('solar_wind_speed', models.FloatField(blank=True, null=True)),
                ('bz_gsm', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('story_text', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='events.spaceweatherevent')),
            ],
        ),
    ]
