# Generated by Django 5.2.7 on 2025-10-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
